services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cognitive_sleep_test
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  jspsych:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: cognitive_sleep_test
      DB_PORT: 3306
    depends_on:
      mysql:
        condition: service_healthy
    command: ["npm", "start"]
